### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by szandara** [grantsrb/PyTorch-A2C#1]
When running your project you get 

  File "/home/zandara/PyTorch-A2C/a2c/__init__.py", line 1, in <module>
    from . import logger, preprocessing, runner, training, updater, utils, models
  File "/home/zandara/PyTorch-A2C/a2c/training.py", line 19, in <module>
    from ml_utils.utils import try_key

not sure where ml_utils is coming from but it looks like your proprietary implementation. 
Please share it or point out what dependency it is

**Comment by grantsrb** [comment]
Thanks for the heads up.

I just attempted to add it to the requirements, so if you pull the latest changes and run `python3 -m pip install --user -r requirements.txt`. Otherwise you can find the `ml_utils` repo [here](https://github.com/grantsrb/ml_utils)

I mainly use this repo for prototyping and have a bad habit of using github as a file transfer system more than a professional tool, so I would recommend you tread carefully when using any code here :)
